package com.aciworldwide.s1adapter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-11T16:59:50.263+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://aciworldwide.com/pim/messages/service/accounts/statements", name = "AcountStatement_PortType")
@XmlSeeAlso({com.aciworldwide.s1adapter.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AcountStatementPortType {

    @WebMethod(operationName = "AccImgSearch")
    @WebResult(name = "responce", targetNamespace = "", partName = "responce")
    public com.aciworldwide.s1adapter.BankAcctImgSrchOutType accImgSearch(
        @WebParam(partName = "request", name = "request", targetNamespace = "")
        com.aciworldwide.s1adapter.BankAcctImgSrchInpType request
    ) throws DepositAcctStmtRs;
    
    @WebMethod(operationName = "DepositStatement")
    @WebResult(name = "response", targetNamespace = "", partName = "response")
    public com.aciworldwide.s1adapter.DepAcctStmtInqOutType depositStatement(
        @WebParam(partName = "request", name = "request", targetNamespace = "")
        com.aciworldwide.s1adapter.DepAcctStmtInqInpType request
    ) throws DepositAcctStmtRs;

    @WebMethod(operationName = "LoanStatement")
    @WebResult(name = "responce", targetNamespace = "", partName = "responce")
    public com.aciworldwide.s1adapter.LoanAcctStmtInqOutType loanStatement(
        @WebParam(partName = "request", name = "request", targetNamespace = "")
        com.aciworldwide.s1adapter.LoanAcctStmtInqInpType request
    ) throws DepositAcctStmtRs;

    @WebMethod(operationName = "CCStatement")
    @WebResult(name = "responce", targetNamespace = "", partName = "responce")
    public com.aciworldwide.s1adapter.CCAcctStmtInqOutType ccStatement(
        @WebParam(partName = "request", name = "request", targetNamespace = "")
        com.aciworldwide.s1adapter.CCAcctStmtInqInpType request
    ) throws DepositAcctStmtRs;

    @WebMethod(operationName = "AccImgTrn")
    @WebResult(name = "responce", targetNamespace = "", partName = "responce")
    public com.aciworldwide.s1adapter.BankAcctTrnImgInqOutType accImgTrn(
        @WebParam(partName = "request", name = "request", targetNamespace = "")
        com.aciworldwide.s1adapter.BankAcctTrnImgInqInpType request
    ) throws DepositAcctStmtRs;
}
